name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

env:
  AZURE_WEBAPP_NAME: InteractHub
  DOTNET_VERSION: '10.0.x'

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore packages
        run: dotnet restore backend/backend.csproj

      - name: Build project
        run: dotnet build backend/backend.csproj --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test backend.Tests/backend.Tests.csproj --configuration Release --no-build

      - name: Publish project
        run: dotnet publish backend/backend.csproj --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./publish

  deploy:
    needs: build
    runs-on: windows-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./publish

      - name: Logout Azure
        run: az logout
        if: always()