name: Build Test and Deploy Render

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

env:
  DOTNET_VERSION: '10.0.x'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore packages
        run: dotnet restore backend/backend.csproj

      - name: Build project
        run: dotnet build backend/backend.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test backend.Tests/backend.Tests.csproj --configuration Release

      - name: Publish project
        run: dotnet publish backend/backend.csproj --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./publish

  deploy-render:
    needs: build

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}